version: "3.9"
services:
  backend:
    build:
      context: ./backend
    command: python app.py
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    depends_on:
      - backend
